### ISSUE TITLE
Nice work！Can it apply to VLMs?

### ISSUE THREAD

**Issue by zhangbaijin** [GATECH-EIC/ACT#1]
Great work!Can it apply to LLaVA1.5, Qwen? How to solve the config?

**Comment by Yuzz1020** [comment]
Thank you for raising this issue, it's a great question! We have conducted some preliminary experiments and observed similar attention sink patterns in VLM. However, we have not yet tested whether the proposed attention calibration technique can be applied to VLM to improve their performance.
