### ISSUE TITLE
Cool! Is the source code of visualizing the attention maps available? I can not find it. Thanks!

### ISSUE THREAD

**Issue by keepsimpler** [GATECH-EIC/ACT#2]

**Comment by Yuzz1020** [comment]
Thank you for your question. You can visualize the attention map by averaging the attention values after applying softmax ([here](https://github.com/GATECH-EIC/ACT/blob/a267af7e70cd277090acbd01d87bb497921d5025/models/llama_modelling_aug.py#L139)) across the heads/layers of your choice, then saving the visualized figure. To better observe the pattern, please reduce the maximum value of the color bar, as we did in our paper.
